name: CI

on:
  pull_request:
    types: [closed]
    branches:
      - master
  push:
    branches:
      - master
    paths-ignore:
      - .vscode

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
      - run: yarn install --frozen-lockfile --non-interactive
      - run: yarn lint
